ROCmSoftwarePlatform/hipCUB

- Jenkinsfile
- docker/dockerfile-build-ubuntu-rock
- docker/dockerfile-install-ubuntu
- Have to test this in Jenkins
> Added Jenkinsfile

- hipcub/include/hipcub/rocprim/device/device_scan.hpp
- test/hipcub/test_hipcub_device_scan.cpp
> Fix order of params in DeviceScan::*Sum, add tests

- README.md
- hipcub/include/hipcub/config.hpp
- hipcub/include/hipcub/hipcub.hpp
- hipcub/include/hipcub/rocprim/thread/thread_operators.hpp
Also show an error if particular headers are included.
> WIP: Add a note to README about including only <hipcub/hipcub.hpp>

- Jenkinsfile
- docker/dockerfile-build-centos
- docker/dockerfile-build-ubuntu-rock
- docker/dockerfile-install-centos
- install
- Adds CentOS and hip-clang jobs
- Needs to pass CI
> Hip clang CI jobs added

- .githooks/pre-commit
- Jenkinsfile
- docker/dockerfile-build-centos
- docker/dockerfile-build-sles
- docker/dockerfile-build-ubuntu-rock
- docker/dockerfile-install-centos
- docker/dockerfile-install-sles
- docker/dockerfile-install-ubuntu
- install
- Fixing dockerfiles
- Fixing pre-commit hooks (I couldn't commit without changing the clang-format)
> Adding SLES support

- test/hipcub/test_hipcub_device_histogram.cpp
> Fix warnings

- .gitignore
- .gitlab-ci.yml
- .gitlab/cmake-run-benchmarks.txt
- CMakeLists.txt
- README.md
- benchmark/CMakeLists.txt
- benchmark/benchmark_block_discontinuity.cpp
- benchmark/benchmark_block_exchange.cpp
- benchmark/benchmark_block_histogram.cpp
- benchmark/benchmark_block_radix_sort.cpp
- benchmark/benchmark_block_reduce.cpp
- benchmark/benchmark_block_scan.cpp
- benchmark/benchmark_device_histogram.cpp
- benchmark/benchmark_device_radix_sort.cpp
- benchmark/benchmark_device_reduce.cpp
- benchmark/benchmark_device_reduce_by_key.cpp
- benchmark/benchmark_device_run_length_encode.cpp
- benchmark/benchmark_device_scan.cpp
- benchmark/benchmark_device_segmented_radix_sort.cpp
- benchmark/benchmark_device_segmented_reduce.cpp
- benchmark/benchmark_device_select.cpp
- benchmark/benchmark_utils.hpp
- benchmark/benchmark_warp_reduce.cpp
- benchmark/benchmark_warp_scan.cpp
- benchmark/cmdparser.hpp
- benchmark/common_benchmark_header.hpp
- cmake/Dependencies.cmake
- test/extra/test_hipcub_package.cpp
- test/hipcub/test_utils.hpp
Add internal benchmark to hipCUB
> Internal benchmark deploy

- .gitlab-ci.yml
- README.md
- benchmark/benchmark_block_discontinuity.cpp
- benchmark/benchmark_block_exchange.cpp
- benchmark/benchmark_block_histogram.cpp
- benchmark/benchmark_block_radix_sort.cpp
- benchmark/benchmark_block_reduce.cpp
- benchmark/benchmark_block_scan.cpp
- benchmark/benchmark_utils.hpp
- benchmark/benchmark_warp_reduce.cpp
- benchmark/benchmark_warp_scan.cpp
- test/hipcub/test_hipcub_block_discontinuity.cpp
- test/hipcub/test_hipcub_block_exchange.cpp
- test/hipcub/test_hipcub_block_histogram.cpp
- test/hipcub/test_hipcub_block_load_store.cpp
- test/hipcub/test_hipcub_block_radix_sort.cpp
- test/hipcub/test_hipcub_block_reduce.cpp
- test/hipcub/test_hipcub_block_scan.cpp
- test/hipcub/test_hipcub_warp_reduce.cpp
- test/hipcub/test_hipcub_warp_scan.cpp
- test/hipcub/test_utils.hpp
* Add amdgpu_flat_work_group_size
* Replace HCC with HIP-clang
> Add amdgpu_flat_work_group_size and replace HCC with HIP-clang

- .gitlab-ci.yml
- cmake/VerifyCompiler.cmake
Change HIP_COMPILER at nvcc case
> Change HIP_COMPILER value at nvcc case 

- .gitlab-ci.yml
- README.md
- cmake/Dependencies.cmake
- cmake/VerifyCompiler.cmake
- hipcub/CMakeLists.txt
- Explicitly add AMDGPU_TARGETS
- Add nvcc to compiler exceptions for building googlebenchmark and googletest
- Update readme
- Update CI
> Develop stream 20200821

- CHANGELOG.md
- CMakeLists.txt
- README.md
Also includes targetid changes.
> Update for ROCm 4.0

- hipcub/include/hipcub/backend/rocprim/iterator/discard_output_iterator.hpp
- hipcub/include/hipcub/iterator/discard_output_iterator.hpp
- test/hipcub/test_hipcub_block_load_store.cpp
> Added discard iterator

- .gitlab-ci.yml
- CMakeLists.txt
- test/extra/CMakeLists.txt
* Update xnack option and added gfx803
* Update gitlab CI
* Move setting of AMDGPU_TARGET before find_package(hip)
> Update xnack option and move setting of AMDGPU_TARGET before find_package(hip)

- docs/conf.py
- hipcub/include/hipcub/backend/rocprim/grid/grid_barrier.hpp
- hipcub/include/hipcub/backend/rocprim/grid/grid_even_share.hpp
- hipcub/include/hipcub/backend/rocprim/grid/grid_mapping.hpp
- hipcub/include/hipcub/backend/rocprim/grid/grid_queue.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/arg_index_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/constant_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/counting_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/discard_output_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/transform_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/thread/thread_load.hpp
- hipcub/include/hipcub/backend/rocprim/thread/thread_reduce.hpp
- hipcub/include/hipcub/backend/rocprim/thread/thread_scan.hpp
- hipcub/include/hipcub/backend/rocprim/thread/thread_search.hpp
- hipcub/include/hipcub/backend/rocprim/thread/thread_store.hpp
- hipcub/include/hipcub/backend/rocprim/util_type.hpp
- hipcub/include/hipcub/grid/grid_barrier.hpp
- hipcub/include/hipcub/grid/grid_even_share.hpp
- hipcub/include/hipcub/grid/grid_mapping.hpp
- hipcub/include/hipcub/grid/grid_queue.hpp
- hipcub/include/hipcub/thread/thread_load.hpp
- hipcub/include/hipcub/thread/thread_reduce.hpp
- hipcub/include/hipcub/thread/thread_scan.hpp
- hipcub/include/hipcub/thread/thread_search.hpp
- hipcub/include/hipcub/thread/thread_store.hpp
- test/hipcub/CMakeLists.txt
- test/hipcub/test_hipcub_grid.cpp
- test/hipcub/test_hipcub_iterators.cpp
- test/hipcub/test_hipcub_thread.cpp
* Add grid algorithms and tests
* Extended the ```cpp_id_attributes``` with ```"__forceinline__"``` and ```"static"```, which reduced the warnings in the documentation generation.
> Develop stream 20210311

- .gitlab-ci.yml
- hipcub/include/hipcub/backend/rocprim/util_ptx.hpp
- hipcub/include/hipcub/backend/rocprim/warp/warp_reduce.hpp
- hipcub/include/hipcub/backend/rocprim/warp/warp_scan.hpp
- hipcub/include/hipcub/config.hpp
- test/hipcub/test_hipcub_block_exchange.cpp
- test/hipcub/test_hipcub_grid.cpp
- test/hipcub/test_hipcub_iterators.cpp
- test/hipcub/test_hipcub_thread.cpp
- test/hipcub/test_hipcub_util_ptx.cpp
- test/hipcub/test_hipcub_warp_reduce.cpp
- test/hipcub/test_hipcub_warp_scan.cpp
- test/hipcub/test_utils.hpp
Warp tests fix and NVIDIA backend fix
> Warp tests fix and NVIDIA backend fix

- .gitlab-ci.yml
- CMakeLists.txt
- cmake/RocmCmakeDependence.cmake
- hipcub/include/hipcub/backend/rocprim/iterator/arg_index_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/cache_modified_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/cache_modified_output_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/constant_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/counting_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/discard_output_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/tex_obj_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/tex_ref_input_iterator.hpp
- hipcub/include/hipcub/backend/rocprim/iterator/transform_input_iterator.hpp
Add iterator_facade for the newer Thrust API
> Add iterator_facade for the newer Thrust API

- .jenkins/common.groovy
- .jenkins/precheckin.groovy
- CMakeLists.txt
- cmake/Dependencies.cmake
- cmake/RocmCmakeDependence.cmake
* Add gfx90a targets
* Check for valid compiler targets using rocm_check_target_ids
> Cherry-pick PR #135 (Add gfx90a targets)

- hipcub/CMakeLists.txt
Summary of proposed changes:
- Include directory updated to include/component_nm structure
- lib directory updated to lib structure with no component_name prefix
> Lib, include target reorg

- test/hipcub/test_hipcub_block_run_length_decode.cpp
Fixing char data generation in test_hipcub_block_run_length_decode
> Fixing char data generation in test_hipcub_block_run_length_decode

- CMakeLists.txt
- cmake/VerifyCompiler.cmake
- test/extra/CMakeLists.txt
SWDEV-345870 - Use actual hip  files rather than using softlinks
> Correct hip path for new directory layout 

- examples/CMakeLists.txt
- examples/block/CMakeLists.txt
- examples/device/CMakeLists.txt
Thanks @cgmb for pointing out their absence.
> Adding copyrights to examples' CMakeLists.txt

- cmake/Dependencies.cmake
See https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/477
> update googlebenchmark version

- cmake/ROCmCMakeBuildToolsDependency.cmake
See #308 for more information.
> HOTFIX: Include FetchContent before usage
