- cmake/ROCMExportTargetsHeaderOnly.cmake
- hipcub/CMakeLists.txt
Fix for PyTorch Compile issue. This modifies the pacakges to remote interface targets for the library in the hipcub-config.cmake files
> Package building fix for PyTorch

- cmake/ROCMExportTargetsHeaderOnly.cmake
- hipcub/CMakeLists.txt
* Fix for PyTorch Compile issue. This modifies the pacakges to remote interface targets for the library in the hipcub-config.cmake files
* modifying hipcub CMakelists for new export target function
> Package building fix for PyTorch (#31)

- install
- New mode of building is added "-r,--relocatable" which is used
for ROCm stack installed in /opt/rocm-ver.
- Below CMAKE parameters are set/overwritten in above mode
CMAKE_INSTALL_PREFIX
CMAKE_PREFIX_PATH
CMAKE_MODULE_PATH
Signed-off-by: Pruthvi Madugundu <mpruthvi@gmail.com>
> HipCUB changes to support multiple ROCM installation

- test/hipcub/test_hipcub_device_partition.cpp
- test/hipcub/test_hipcub_device_select.cpp
- test/hipcub/test_hipcub_grid.cpp
This will fix the build failures in the develop branch, it is from the gfx1030/navi21 PR.  Also gets rid of some googletest deprecation warnings, as we had to update to gtest 1.10.
> Fixing test build failure and deprecated warning

- hipcub/include/hipcub/backend/rocprim/hipcub.hpp
Customer request to have discard output iterator added to the backend header.  I don't see any downside to this?
> Adding discard output iterator to backend header

- CMakeLists.txt
- cmake/Dependencies.cmake
- test/hipcub/common_test_header.hpp
- test/hipcub/test_hipcub_block_discontinuity.cpp
- test/hipcub/test_hipcub_block_exchange.cpp
- test/hipcub/test_hipcub_block_histogram.cpp
- test/hipcub/test_hipcub_block_load_store.cpp
- test/hipcub/test_hipcub_block_radix_sort.cpp
- test/hipcub/test_hipcub_block_reduce.cpp
- test/hipcub/test_hipcub_block_scan.cpp
- test/hipcub/test_hipcub_device_histogram.cpp
- test/hipcub/test_hipcub_device_radix_sort.cpp
- test/hipcub/test_hipcub_device_reduce.cpp
- test/hipcub/test_hipcub_device_reduce_by_key.cpp
- test/hipcub/test_hipcub_device_run_length_encode.cpp
- test/hipcub/test_hipcub_device_scan.cpp
- test/hipcub/test_hipcub_device_segmented_radix_sort.cpp
- test/hipcub/test_hipcub_device_segmented_reduce.cpp
- test/hipcub/test_hipcub_device_select.cpp
- test/hipcub/test_hipcub_util_ptx.cpp
- test/hipcub/test_hipcub_warp_reduce.cpp
- test/hipcub/test_hipcub_warp_scan.cpp
Opt-in to use hipMallocManaged with HIPCUB_USE_HMM=1 environment variable.
Do not merge PR until approved by PM.
> Cherry-picking HMM unit test support for ROCm 4.3

- .jenkins/common.groovy
- CHANGELOG.md
- CMakeLists.txt
- cmake/Dependencies.cmake
- test/hipcub/common_test_header.hpp
- test/hipcub/test_hipcub_block_discontinuity.cpp
- test/hipcub/test_hipcub_block_exchange.cpp
- test/hipcub/test_hipcub_block_histogram.cpp
- test/hipcub/test_hipcub_block_load_store.cpp
- test/hipcub/test_hipcub_block_radix_sort.cpp
- test/hipcub/test_hipcub_block_reduce.cpp
- test/hipcub/test_hipcub_block_scan.cpp
- test/hipcub/test_hipcub_device_histogram.cpp
- test/hipcub/test_hipcub_device_radix_sort.cpp
- test/hipcub/test_hipcub_device_reduce.cpp
- test/hipcub/test_hipcub_device_reduce_by_key.cpp
- test/hipcub/test_hipcub_device_run_length_encode.cpp
- test/hipcub/test_hipcub_device_scan.cpp
- test/hipcub/test_hipcub_device_segmented_radix_sort.cpp
- test/hipcub/test_hipcub_device_segmented_reduce.cpp
- test/hipcub/test_hipcub_device_select.cpp
- test/hipcub/test_hipcub_util_ptx.cpp
- test/hipcub/test_hipcub_warp_reduce.cpp
- test/hipcub/test_hipcub_warp_scan.cpp
To enable, run tests with HIPCUB_USE_HMM=1 environment variable set on supported hardware.
> Enabling HMM unit test support

- CHANGELOG.md
- CMakeLists.txt
- cmake/ROCMExportTargetsHeaderOnly.cmake
Switch rocm_export_targets_header_only to use rocm_install rather than install.
#152 did not update documentation.
> Update changelog & fix rocm_export_targets_header_only

- CMakeLists.txt
As hipCUB is a header-only library, use the HEADER_ONLY option to rocm_create_package in the latest version of rocm-cmake to prevent generation of an empty runtime package. Also update the dependency on rocprim to be a dependency on rocprim-devel.
> Remove runtime package

- CHANGELOG.md
- CMakeLists.txt
To match the industry-standard package naming, rocprim-devel is called rocprim-dev on Debian.
> Rename rocprim-devel dependency on debian

- hipcub/include/hipcub/backend/rocprim/device/device_scan.hpp
Add size_limit paramter usage to device scan rocPRIM backend
> Add size_limit paramter usage to device scan rocPRIM backend

- test/hipcub/test_hipcub_block_run_length_decode.cpp
According to https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution, char is not on the list of supported datatypes for std::uniform_int_distribution.  I'm not sure how the test compiles on Linux, but with HIP on Windows the test fails to compile (see log below).  I've decided to remove the test params with char in them from Windows for now, but @neon60  you have recommendations for replacement test parameters let me know and I'll put them in.  
[1/75] Building CXX object test/hipcub/CMakeFiles/test_hip...gth_decode.dir/test_hipcub_block_run_length_decode.cpp.obj
FAILED: test/hipcub/CMakeFiles/test_hipcub_block_run_length_decode.dir/test_hipcub_block_run_length_decode.cpp.obj
C:\hip\bin\clang++.exe -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -D__HIP_PLATFORM_AMD__=1 …
> Disabling char datatype for block_run_length_decode unit test for Windows

- hipcub/include/hipcub/backend/rocprim/thread/thread_load.hpp
- `grid_barrier` uses `thread_load` for loading values from global memory.
- `thread_load` was previously implemented with two inline assembly statements. This gave opportunity to the compiler to inject instructions between the two, in our case it injected the comparison **before** the `s_waitcnt`.
- Changed it to a single assembly statement, thereby no instruction can be inserted between the load and the wait.
> Fixed hang in test_hipcub_grid on gfx1030

- docs/requirements.txt
This should get hipCUB documentation building again.  Previous error was due to old version of breathe being used.
> Bump up breathe version to 4.33.1

- hipcub/CMakeLists.txt
Summary of proposed changes:
- Original Header File Dump enabled for version header file wrapper to support backward Compatibility for PT/TF
- Depends on wrapper functions of rocm-cmake version https://github.com/RadeonOpenCompute/rocm-cmake/commit/d108dbf05e029996d5d7bcbe258abb1166547a30Summary of proposed changes:
> ENABLE ORIGINAL FILE DUMP IN VERSION HDR FILE WRAPPER FOR BKWDCOMP

- hipcub/CMakeLists.txt
Summary of proposed changes:
- Original Header File Dump enabled for version header wrapper to support backward Compatibility for PT/TF
- ROCM-CMAKE Version Depend https://github.com/RadeonOpenCompute/rocm-cmake/commit/d108dbf05e029996d5d7bcbe258abb1166547a30
> Enable Origin header file dump option for wrapper

- toolchain-linux.cmake
Proposed Changes:
- Update HIP bin prefix path to rocm_path (rocm_path/bin will be used for hipcc as per the reorg structure)
> HIP Bin prefix path updated to rocm_path as per reorg structure

- CMakeLists.txt
- hipcub/CMakeLists.txt
The backwards compatibility headers should not be generated or installed on Windows.
> HOTFIX: Remove backwards compatibility headers on Windows

- test/CMakeLists.txt
When creating the CTestTestfile for installation, the `rocm_install` statement was incorrectly removed. This restores it.
> HOTFIX: Restore incorrectly removed rocm_install

- test/hipcub/test_hipcub_block_run_length_decode.cpp
Fixes out of bounds access in `test_hipcub_block_run_length_decode.cpp`.
> Fix out of bounds access in test

- test/CMakeLists.txt
#208 unintentionally removed the statement installing the test executables to the tests package. This restores that.
> Restore test executables in tests package

- cmake/Dependencies.cmake
Additional code was added previously to allow for GTest to be found in CMake package module mode. However because different targets are created when including GTest via module mode than via config mode, library aliases were attempted. Unfortunately, when library targets are imported using find_package they are imported at a scope which prevents these aliases from working. While there are ways to get around this in later versions of CMake, we cannot use them without increasing the minimum CMake version. As CMake is moving towards using config mode for GTest anyways, using solely config mode should be sufficient.
> Only search for GTest using config mode

- test/hipcub/test_hipcub_device_radix_sort.hpp
Modify the device_radix_sort test (when requiring more than 4G) to check the memory before running the test. In this case, for Navi32 in the multiVF system it is necessary to keep at least 10% of the total global memory.
> Navi32 multiVF failing test

- test/hipcub/test_hipcub_device_radix_sort.hpp
This 5.7 cherry pick fixes test device_radix_sort for Navi32 Multi VF.
> 5.7 cherry pick - fix test device_radix_sort

- test/hipcub/test_hipcub_iterators.cpp
When I tried running these tests on gfx94x, I did not see any of the SCOPED_TRACE messages.  I think SCOPED_TRACE only prints if there's an explicit assert failure in gtest in the same scope.(https://github.com/google/googletest/blob/main/docs/advanced.md#using-assertions-in-sub-routines)
I think GTEST_SKIP would serve our purposes better.
> Switch to GTEST_SKIP for gfx94x checks

- hipcub/include/hipcub/backend/rocprim/util_allocator.hpp
silences warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
Fixes SWDEV-328782.
> silence nodiscard warning for FreeAllCached()

- cmake/VerifyCompiler.cmake
From ROCm 5.7 onwards the HIP CMake package should be findable/usable for both AMD and NVIDIA platforms.
Additionally, setting [`NO_DEFAULT_PATH`](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure) blocks `find_package` from using the CMAKE_PREFIX_PATH, which is often used to specify the locations of installations of other packages, so that has been removed.
> Always use config-mode search for HIP

- docs/.doxygen/Doxyfile
- hipcub/include/hipcub/backend/rocprim/block/block_merge_sort.hpp
- hipcub/include/hipcub/backend/rocprim/block/block_radix_rank.hpp
- hipcub/include/hipcub/backend/rocprim/block/block_raking_layout.hpp
- hipcub/include/hipcub/backend/rocprim/block/block_run_length_decode.hpp
- hipcub/include/hipcub/backend/rocprim/block/block_shuffle.hpp
- hipcub/include/hipcub/backend/rocprim/thread/thread_scan.hpp
- hipcub/include/hipcub/backend/rocprim/warp/warp_merge_sort.hpp
* Turned on WARN_AS_ERROR in the Doxyfile
* Added "backend/" to excluded directories in Doxyfile, since it just makes calls into CUB/rocPRIM, each of which have their own existing documentation.
* Fixed scenarios generating warnings when the documentation is built:
- Removed unsupported tags/commands
- Added escape characters
- Added missing parameter documentation
>  Treat Doxygen warnings as errors

- benchmark/benchmark_block_adjacent_difference.cpp
- benchmark/benchmark_block_discontinuity.cpp
- benchmark/benchmark_device_memory.cpp
- benchmark/benchmark_device_select.cpp
- benchmark/benchmark_utils.hpp
- benchmark/benchmark_warp_scan.cpp
- benchmark/cmdparser.hpp
- test/hipcub/bfloat16.hpp
- test/hipcub/experimental/sparse_matrix.hpp
- test/hipcub/half.hpp
- test/hipcub/identity_iterator.hpp
- test/hipcub/test_hipcub_block_adjacent_difference.cpp
- test/hipcub/test_hipcub_block_discontinuity.cpp
- test/hipcub/test_hipcub_device_reduce.cpp
- test/hipcub/test_hipcub_device_scan.cpp
- test/hipcub/test_hipcub_device_segmented_reduce.cpp
- test/hipcub/test_hipcub_device_spmv.cpp
- test/hipcub/test_hipcub_grid.cpp
- test/hipcub/test_hipcub_iterators.cpp
- test/hipcub/test_hipcub_util_ptx.cpp
- test/hipcub/test_hipcub_warp_reduce.cpp
- test/hipcub/test_hipcub_warp_scan.cpp
- test/hipcub/test_utils_custom_test_types.hpp
- test/hipcub/test_utils_data_generation.hpp
Fixed a number of issues that static analysis picked up:
- Made some functions const since they don't modify member state
- Made some parameters const, since they're never modified
- Fixes for several benchmark/test functions
- Removed unused variable declarations
- Added missing input data transfer from host to device 
- Added some member variables to constructor initializer list 
- Added override keyword in several places 
- Fixed up item placeholders in some printf statements
> Fix cpp-check reported issues

- benchmark/benchmark_block_adjacent_difference.cpp
- benchmark/benchmark_block_discontinuity.cpp
- benchmark/benchmark_device_memory.cpp
- benchmark/benchmark_device_select.cpp
- benchmark/benchmark_utils.hpp
- benchmark/benchmark_warp_scan.cpp
- benchmark/cmdparser.hpp
- test/hipcub/bfloat16.hpp
- test/hipcub/experimental/sparse_matrix.hpp
- test/hipcub/half.hpp
- test/hipcub/identity_iterator.hpp
- test/hipcub/test_hipcub_block_adjacent_difference.cpp
- test/hipcub/test_hipcub_block_discontinuity.cpp
- test/hipcub/test_hipcub_device_reduce.cpp
- test/hipcub/test_hipcub_device_scan.cpp
- test/hipcub/test_hipcub_device_segmented_reduce.cpp
- test/hipcub/test_hipcub_device_spmv.cpp
- test/hipcub/test_hipcub_grid.cpp
- test/hipcub/test_hipcub_iterators.cpp
- test/hipcub/test_hipcub_util_ptx.cpp
- test/hipcub/test_hipcub_warp_reduce.cpp
- test/hipcub/test_hipcub_warp_scan.cpp
- test/hipcub/test_utils_custom_test_types.hpp
- test/hipcub/test_utils_data_generation.hpp
Fix cpp-check reported issues
Fixed a number of issues that static analysis picked up:
- Made some functions const since they don't modify member state
- Made some parameters const, since they're never modified
- Fixes for several benchmark/test functions
- Removed unused variable declarations
- Added missing input data transfer from host to device
- Added some member variables to constructor initializer list
- Added override keyword in several places
- Fixed up item placeholders in some printf statements
- Removed host to data transfer from memcpy benchmark.
- Since this benchmark only tests memcpy performance between device buffers, we don't really need to copy data into these from the host.
> Cherry-pick cpp-check reported fixes

- hipcub/include/hipcub/backend/rocprim/util_allocator.hpp
Incrementing an iterator that has been erased from an `std::multiset` is invalid. However, `std::multiset::erase(iter)` returns the next iterator value.
Incrementing the invalidated iterator results in a segmentation fault. This PR uses the returned iterator instead.
> Avoid a segmentation fault when clearing cached blocks

- hipcub/include/hipcub/backend/rocprim/util_allocator.hpp
Same as https://github.com/ROCmSoftwarePlatform/hipCUB/pull/297, but the customer wants this in for 6.0
> Avoid a segmentation fault when clearing cached blocks (#297)

- cmake/ROCmCMakeBuildToolsDependency.cmake
The `find_package` call for rocm-cmake was moved out of Dependencies.cmake for ordering reasons, but the `include(FetchContent)` call was not copied.
> Include FetchContent before usage

- hipcub/include/hipcub/backend/rocprim/util_allocator.hpp
Do not merge until PM approval given.
> Cherry-pick: Avoid a segmentation fault when clearing cached blocks (#297)
